name: Deploy Laravel to A2 Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to A2 Hosting via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_SERVER }}
          port: 22
          user: ${{ secrets.SFTP_USERNAME }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          localDir: './'
          remoteDir: './iedu.nakasha.store/'
          options: '--verbose --delete --only-newer --parallel=5 --exclude-glob .git/ --exclude-glob node_modules/ --exclude-glob .github/ --exclude-glob tests/ --exclude-glob storage/logs/'

