name: Deploy Laravel to A2 Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
# adicionando isso para testar o deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clear git rename tracking
        run: |
          git rm -rf --cached app/Http/Controllers/Api 2>/dev/null || true

      - name: Deploy Laravel to A2 Hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
          dangerous-clean-slate: false
          atomic: false
          log-level: verbose
          exclude: |
            **/.git/**
            **/node_modules/**
            **/.github/**
            **/.vscode/**
            **/README.md
            **/.env.example
            **/tests/**
            **/sh files/**
            **/*.md
            **/TWILIO_SETUP.md
            **/FORM_ENGINE_COMPLIANCE_REPORT.md
            **/DOCUMENTACAO_ESTRUTURA_SISTEMA.md
            **/documentacao_api_v1.md
            **/.env.production
            **/.env.development
            **/.env.staging
            **/.env.testing
            **/.env.local



