name: Deploy to A2 Hosting IEDU Nakasha Store

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for proper versioning

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Get npm cache directory
      id: npm-cache
      shell: bash
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Cache Angular build
      uses: actions/cache@v3
      with:
        path: |
          .angular/cache
        key: ${{ runner.os }}-angular-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-angular-

    - name: Build Angular app
      run: npm run build -- --configuration=production
      env:
        NODE_ENV: production

    - name: Verify build output
      run: |
        if [ ! -d "dist" ]; then
          echo "Build failed - dist directory not found"
          exit 1
        fi

    - name: Deploy to A2 Hosting
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./iedu.nakasha.store/
        dangerous-clean-slate: false # Evita deletar arquivos existentes
        exclude: |

            **/.git/**
            **/.github/**
            **/.vscode/**
            **/node_modules/**
            **/vendor/**
            **/tests/**
            **/.env
            **/.env.*
            **/.gitignore
            **/.gitattributes
            **/.editorconfig
            **/phpunit.xml
            **/package.json
            **/package-lock.json
            **/vite.config.js
            **/webpack.mix.js
            **/*.md
            **/database/database.sqlite
            **/storage/logs/**
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/storage/framework/views/**
            **/sh files/**
            **/TWILIO_SETUP.md
            **/FORM_ENGINE_COMPLIANCE_REPORT.md
            **/DOCUMENTACAO_ESTRUTURA_SISTEMA.md
            **/documentacao_api_v1.md
            **/public/hot/**
            **/public/storage/**
            **/public/build/**
            **/public/js/**
            **/public/css/**
            **/public/img/**
            **/public/fonts/**
            **/public/favicon.ico
            **/public/robots.txt
            **/public/sitemap.xml
