name: Deploy Laravel to A2 Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to A2 Hosting via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: ./iedu.nakasha.store/
          dangerous-clean-slate: false
          exclude: |
            **/.git/**
            **/.github/**
            **/.vscode/**
            **/node_modules/**
            **/vendor/**
            **/tests/**
            **/.env
            **/.env.*
            **/.gitignore
            **/.gitattributes
            **/.editorconfig
            **/phpunit.xml
            **/package.json
            **/package-lock.json
            **/vite.config.js
            **/webpack.mix.js
            **/*.md
            **/database/database.sqlite
            **/storage/logs/**
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/storage/framework/views/**
            **/sh files/**
            **/TWILIO_SETUP.md
            **/FORM_ENGINE_COMPLIANCE_REPORT.md
            **/DOCUMENTACAO_ESTRUTURA_SISTEMA.md
            **/documentacao_api_v1.md

