name: Deploy Laravel to A2 Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Laravel app (excluding public) via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_APP_DIR }}
          dangerous-clean-slate: false
          exclude: |
            public/**
            **/.git/**
            **/node_modules/**
            **/.github/**
            **/.vscode/**
            **/README.md
            **/.env.example
            **/tests/**
            **/sh files/**
            **/*.md
            **/TWILIO_SETUP.md
            **/FORM_ENGINE_COMPLIANCE_REPORT.md
            **/DOCUMENTACAO_ESTRUTURA_SISTEMA.md
            **/documentacao_api_v1.md

      - name: Deploy public directory to webroot via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: ${{ secrets.FTP_PUBLIC_DIR }}
          dangerous-clean-slate: false
          exclude: |
            .htaccess.sample


