name: Deploy Laravel to A2 Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Laravel Core Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
          dangerous-clean-slate: false
          exclude: |
            **/.git/**
            **/node_modules/**
            **/.github/**
            **/.vscode/**
            **/README.md
            **/.env.example
            **/tests/**
            **/sh files/**
            **/*.md
            **/TWILIO_SETUP.md
            **/FORM_ENGINE_COMPLIANCE_REPORT.md
            **/DOCUMENTACAO_ESTRUTURA_SISTEMA.md
            **/documentacao_api_v1.md

      - name: Set Permissions via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            chmod -R 755 storage
            chmod -R 755 bootstrap/cache
            find storage -type f -exec chmod 644 {} \;
            find storage -type d -exec chmod 755 {} \;
            find bootstrap/cache -type f -exec chmod 644 {} \;
            find bootstrap/cache -type d -exec chmod 755 {} \;



