name: Deploy to A2 Hosting IEDU Nakasha Store

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Laravel to A2 Hosting via SFTP
        uses: easingthemes/ssh-deploy@v4.1.10
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.FTP_SERVER }}
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          REMOTE_PORT: 22
          SOURCE: "./"
          TARGET: "${{ secrets.REMOTE_PATH }}"
          ARGS: "-rltgoDzvO --delete"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          EXCLUDE: "/node_modules/, /vendor/, /.git/, /.github/, /tests/, /storage/logs/, /.env, /.env.*, /sh files/"
          SCRIPT_AFTER: |
            cd ${{ secrets.REMOTE_PATH }}
            find . -type f -name ".env*" -delete
            echo "Deploy concluído!"
